var nodes = {};
var edges = {};
nodes['xp'] = { label: 'XP', mass: 3, origin: true, cssClass: 'method'};
nodes['agile_manifesto'] = { label: 'Agile Manifesto', mass: 3, origin: true, cssClass: 'method'};
nodes['agile_manifesto'] = { label: 'Agile Manifesto', mass: 3, origin: true, cssClass: 'method'};
nodes['scrum'] = { label: 'Scrum', mass: 3, origin: true, cssClass: 'method'};
nodes['scrum'] = { label: 'Scrum', mass: 3, origin: true, cssClass: 'method'};
nodes['lean'] = { label: 'Lean', mass: 3, origin: true, cssClass: 'method'};
nodes['customer_satisfaction'] = { label: 'Customer Satisfaction', mass: 2, cssClass: 'attr'};
edges['xpcustomer_satisfaction'] = { nodeA: 'xp', nodeB: 'customer_satisfaction', weight: 75}
edges['agile_manifestocustomer_satisfaction'] = { nodeA: 'agile_manifesto', nodeB: 'customer_satisfaction', weight: 75}
nodes['teamwork'] = { label: 'Teamwork', mass: 2, cssClass: 'attr'};
edges['xpteamwork'] = { nodeA: 'xp', nodeB: 'teamwork', weight: 60}
nodes['equal_partners'] = { label: 'Equal Partners', mass: 2, cssClass: 'attr'};
edges['xpequal_partners'] = { nodeA: 'xp', nodeB: 'equal_partners', weight: 55}
nodes['collaborators'] = { label: 'Collaborators', mass: 2, cssClass: 'attr'};
edges['xpcollaborators'] = { nodeA: 'xp', nodeB: 'collaborators', weight: 50}
nodes['high_productivity'] = { label: 'High Productivity', mass: 2, cssClass: 'attr'};
edges['xphigh_productivity'] = { nodeA: 'xp', nodeB: 'high_productivity', weight: 45}
nodes['self_organizing'] = { label: 'Self-Organizing', mass: 2, cssClass: 'attr'};
edges['xpself_organizing'] = { nodeA: 'xp', nodeB: 'self_organizing', weight: 40}
edges['agile_manifestoself_organizing'] = { nodeA: 'agile_manifesto', nodeB: 'self_organizing', weight: 25}
edges['scrumself_organizing'] = { nodeA: 'scrum', nodeB: 'self_organizing', weight: 35}
edges['leanself_organizing'] = { nodeA: 'lean', nodeB: 'self_organizing', weight: 55}
nodes['honest_planning'] = { label: 'Honest Planning', mass: 2, cssClass: 'attr'};
edges['xphonest_planning'] = { nodeA: 'xp', nodeB: 'honest_planning', weight: 35}
nodes['sprint'] = { label: 'Sprint', mass: 2, cssClass: 'attr'};
edges['xpsprint'] = { nodeA: 'xp', nodeB: 'sprint', weight: 30}
edges['scrumsprint'] = { nodeA: 'scrum', nodeB: 'sprint', weight: 50}
nodes['face_to_face_communication'] = { label: 'Face-to-face communication', mass: 2, cssClass: 'attr'};
edges['agile_manifestoface_to_face_communication'] = { nodeA: 'agile_manifesto', nodeB: 'face_to_face_communication', weight: 75}
edges['agile_manifestoface_to_face_communication'] = { nodeA: 'agile_manifesto', nodeB: 'face_to_face_communication', weight: 50}
edges['scrumface_to_face_communication'] = { nodeA: 'scrum', nodeB: 'face_to_face_communication', weight: 25}
nodes['courage'] = { label: 'Courage', mass: 2, cssClass: 'attr'};
edges['xpcourage'] = { nodeA: 'xp', nodeB: 'courage', weight: 10}
edges['scrumcourage'] = { nodeA: 'scrum', nodeB: 'courage', weight: 55}
nodes['individuals'] = { label: 'Individuals', mass: 2, cssClass: 'attr'};
edges['agile_manifestoindividuals'] = { nodeA: 'agile_manifesto', nodeB: 'individuals', weight: 75}
edges['agile_manifestoindividuals'] = { nodeA: 'agile_manifesto', nodeB: 'individuals', weight: 55}
nodes['collaborate_with_customers'] = { label: 'Collaborate with Customers', mass: 2, cssClass: 'attr'};
edges['agile_manifestocollaborate_with_customers'] = { nodeA: 'agile_manifesto', nodeB: 'collaborate_with_customers', weight: 65}
edges['agile_manifestocollaborate_with_customers'] = { nodeA: 'agile_manifesto', nodeB: 'collaborate_with_customers', weight: 60}
nodes['respond_to_change'] = { label: 'Respond to Change', mass: 2, cssClass: 'attr'};
edges['xprespond_to_change'] = { nodeA: 'xp', nodeB: 'respond_to_change', weight: 65}
edges['agile_manifestorespond_to_change'] = { nodeA: 'agile_manifesto', nodeB: 'respond_to_change', weight: 60}
edges['agile_manifestorespond_to_change'] = { nodeA: 'agile_manifesto', nodeB: 'respond_to_change', weight: 70}
edges['scrumrespond_to_change'] = { nodeA: 'scrum', nodeB: 'respond_to_change', weight: 10}
nodes['working_software'] = { label: 'Working Software', mass: 2, cssClass: 'attr'};
edges['xpworking_software'] = { nodeA: 'xp', nodeB: 'working_software', weight: 70}
edges['agile_manifestoworking_software'] = { nodeA: 'agile_manifesto', nodeB: 'working_software', weight: 70}
edges['agile_manifestoworking_software'] = { nodeA: 'agile_manifesto', nodeB: 'working_software', weight: 65}
edges['scrumworking_software'] = { nodeA: 'scrum', nodeB: 'working_software', weight: 45}
edges['leanworking_software'] = { nodeA: 'lean', nodeB: 'working_software', weight: 60}
nodes['sustainable_development_constant_pace'] = { label: 'Sustainable Development; constant pace', mass: 2, cssClass: 'attr'};
edges['agile_manifestosustainable_development_constant_pace'] = { nodeA: 'agile_manifesto', nodeB: 'sustainable_development_constant_pace', weight: 40}
nodes['technical_excellence'] = { label: 'Technical Excellence', mass: 2, cssClass: 'attr'};
edges['agile_manifestotechnical_excellence'] = { nodeA: 'agile_manifesto', nodeB: 'technical_excellence', weight: 35}
nodes['eliminate_waste'] = { label: 'Eliminate waste', mass: 2, cssClass: 'attr'};
edges['leaneliminate_waste'] = { nodeA: 'lean', nodeB: 'eliminate_waste', weight: 75}
nodes['feedback'] = { label: 'Feedback', mass: 2, cssClass: 'attr'};
edges['xpfeedback'] = { nodeA: 'xp', nodeB: 'feedback', weight: 25}
edges['leanfeedback'] = { nodeA: 'lean', nodeB: 'feedback', weight: 70}
nodes['decide_as_late_as_possible'] = { label: 'Decide as late as possible', mass: 2, cssClass: 'attr'};
edges['leandecide_as_late_as_possible'] = { nodeA: 'lean', nodeB: 'decide_as_late_as_possible', weight: 65}
nodes['build_integrity_in'] = { label: 'Build integrity in', mass: 2, cssClass: 'attr'};
edges['leanbuild_integrity_in'] = { nodeA: 'lean', nodeB: 'build_integrity_in', weight: 50}
nodes['holistic'] = { label: 'Holistic', mass: 2, cssClass: 'attr'};
edges['scrumholistic'] = { nodeA: 'scrum', nodeB: 'holistic', weight: 75}
edges['leanholistic'] = { nodeA: 'lean', nodeB: 'holistic', weight: 45}
nodes['overlapping_phases'] = { label: 'Overlapping Phases', mass: 2, cssClass: 'attr'};
edges['scrumoverlapping_phases'] = { nodeA: 'scrum', nodeB: 'overlapping_phases', weight: 70}
nodes['cross_functional_teams'] = { label: 'Cross-Functional Teams', mass: 2, cssClass: 'attr'};
edges['scrumcross_functional_teams'] = { nodeA: 'scrum', nodeB: 'cross_functional_teams', weight: 65}
nodes['practices'] = { label: 'Practices', mass: 2, cssClass: 'attr'};
edges['scrumpractices'] = { nodeA: 'scrum', nodeB: 'practices', weight: 60}
nodes['predefined_roles'] = { label: 'Predefined Roles', mass: 2, cssClass: 'attr'};
edges['scrumpredefined_roles'] = { nodeA: 'scrum', nodeB: 'predefined_roles', weight: 55}
nodes['backlog'] = { label: 'Backlog', mass: 2, cssClass: 'attr'};
edges['scrumbacklog'] = { nodeA: 'scrum', nodeB: 'backlog', weight: 40}
nodes['commitment'] = { label: 'Commitment', mass: 2, cssClass: 'attr'};
edges['scrumcommitment'] = { nodeA: 'scrum', nodeB: 'commitment', weight: 75}
nodes['focus'] = { label: 'Focus', mass: 2, cssClass: 'attr'};
edges['scrumfocus'] = { nodeA: 'scrum', nodeB: 'focus', weight: 70}
nodes['openness'] = { label: 'Openness', mass: 2, cssClass: 'attr'};
edges['scrumopenness'] = { nodeA: 'scrum', nodeB: 'openness', weight: 65}
nodes['respect'] = { label: 'Respect', mass: 2, cssClass: 'attr'};
edges['scrumrespect'] = { nodeA: 'scrum', nodeB: 'respect', weight: 60}
